-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgPSTKd9v7DNBKhQ9n
+OLq9ZQzrFnFok3PgOdOTS42ThKgCgYIKoZIzj0DAQehRANCAASa4LXlCirMQkFG
i2ss1iuqUGxrV/CMxeAuR0LWduznXt3SNa70jnYfZA4rjz8uV06keAS2z2ZzJHyY
eNgTxgOl
-----END PRIVATE KEY-----