//
//  Color+Extensions.swift
//  meal.advisor.ios
//
//  Brand and semantic color helpers
//

import SwiftUI

extension Color {
    // Note: Primary brand colors come from Asset Symbols generated by Xcode 15+
    // Use Color.primaryOrange and Color.accentGreen provided by the asset catalog.

    // Semantic wrappers for readability
    static let cardBackground = Color(.systemBackground)
    static let primaryText = Color(.label)
    static let secondaryText = Color(.secondaryLabel)
}
